'use client';

import { useEffect, useRef } from 'react';
import { Archive, X } from 'lucide-react';
import styles from './recurring.module.css';

interface ArchiveRecurringModalProps {
  onConfirm: () => void;
  onCancel: () => void;
  isArchiving?: boolean;
}

export function ArchiveRecurringModal({
  onConfirm,
  onCancel,
  isArchiving = false,
}: ArchiveRecurringModalProps) {
  const modalRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && !isArchiving) onCancel();
    };
    document.addEventListener('keydown', handleEscape);
    
    // Lock scroll
    document.body.style.overflow = 'hidden';
    
    return () => {
      document.removeEventListener('keydown', handleEscape);
      document.body.style.overflow = 'unset';
    };
  }, [onCancel, isArchiving]);

  return (
    <div className={styles.modalOverlay}>
      <div 
        className={styles.modalContent} 
        ref={modalRef}
        role="dialog"
        aria-labelledby="archive-modal-title"
        aria-describedby="archive-modal-desc"
      >
        <button 
          type="button"
          onClick={onCancel}
          className={styles.modalClose}
          disabled={isArchiving}
          aria-label="Close dialog"
        >
          <X size={20} />
        </button>

        <div className={styles.modalHeader}>
          <div className={styles.modalIconArchived}>
            <Archive size={24} />
          </div>
          <h2 id="archive-modal-title" className={styles.modalTitle}>Archive Recurring Rule?</h2>
        </div>

        <div id="archive-modal-desc" className={styles.modalBody}>
          <p className={styles.modalText}>
            Are you sure you want to archive this schedule?
          </p>
          <p className={styles.modalText}>
            This action will permanently stop this rule from generating new transactions. Existing transactions generated by this rule will remain in your ledger.
          </p>
        </div>

        <div className={styles.modalFooter}>
          <button
            type="button"
            onClick={onCancel}
            className={styles.modalBtnCancel}
            disabled={isArchiving}
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={onConfirm}
            className={styles.modalBtnArchive}
            disabled={isArchiving}
          >
            {isArchiving ? 'Archiving...' : 'Yes, Archive Rule'}
          </button>
        </div>
      </div>
    </div>
  );
}
